routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
$slugPattern = '[a-z0-9\-]+';

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/', 'PostController@index')->name('posts.index');
Route::get('/{slug}', 'PostController@show')->name('posts.show')->where('slug', $slugPattern);
Route::get('/category/{slug}', 'PostController@category')->name('posts.category')->where('slug', $slugPattern);
Route::get('/user/{id}', 'PostController@user')->name('posts.user')->where('id', '[0-9]+');

Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'as' => 'admin.', 'middleware' => 'auth'], function () {
    Route::resource('posts', 'PostController');
});

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
  public function posts(){
    return $this->hasMany('App\Post');
  }
}

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{

    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'posts';

    /**
     * The database primary key value.
     *
     * @var string
     */
    protected $primaryKey = 'id';

    /**
     * Attributes that should be mass-assignable.
     *
     * @var array
     */
    protected $fillable = ['name', 'slug', 'content', 'category_id', 'user_id'];

    public function category(){
      return $this->belongsTo('App\Category');
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function getExcerpt($max_words = 100, $ending = "...") {
        $text = strip_tags($this->html);
        $words = explode(' ', $text);
        if (count($words) > $max_words) {
            return implode(' ', array_slice($words, 0, $max_words)) . $ending;
        }
        return $text;
    }

    public function getExtrait(){
            $html =  substr($this->content, 0, 300) ;
            return $html;
        }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function isAdmin(){
      return $this->role === 'admin';
    }
}

app/Http/Controllers/Admin/Controller.php
<?php

namespace App\Http\Controllers\Admin;

class Controller extends \App\Http\Controllers\Controller {

}

app/Http/Controllers/Admin/PostController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Category;
use App\Http\Requests\PostRequest;
use App\Post;
use App\User;
use Illuminate\Support\Facades\Gate;
use Illuminate\Support\Facades\Auth;
use App\Repository\PostRepository;


class PostController extends \App\Http\Controllers\Controller {

    private $post_model;
    private $category_model;
    private $user_model;
    private $post_r;

    public function __construct(Post $post_model, Category $category_model, User $user_model,PostRepository $post_r){
      $this->post_model = $post_model;
      $this->category_model = $category_model;
      $this->user_model = $user_model;
      $this->post_r = $post_r;
    }

    public function index(){
      $this->authorize('view', Post::class);
      $posts = $this->post_r->getPosts()->paginate(10);
      return view('admin.posts.index',[
        'posts' => $posts
      ]);
    }

    public function create(){
      $this->authorize('create', Post::class);
      $post = new Post();
      $categories = Category::pluck('name', 'id');
      $users = User::pluck('name', 'id');
      return view('admin.posts.new', [
          'post' => $post,
          'categories' => $categories,
          'users' => $users
      ]);
    }

    public function store(PostRequest $request){
      $this->post_model->newQuery()->create($this->params($request));
      return redirect()->route('admin.posts.index')->with('success','Votre article a été crée');
    }

    public function edit(Post $post){
      $this->authorize('update', $post);
      $categories = $this->category_model->newQuery()->pluck('name','id');
      $users = $this->user_model->newQuery()->pluck('name', 'id');
      return view('admin.posts.new',[
          'post' => $post,
          'categories' => $categories,
          'users' => $users
      ]);
    }

    public function update(PostRequest $request, Post $post){
      $this->authorize('update', $post);
      $post->update($this->params($request));
      return redirect()->route('admin.posts.index')->with('success','Votre article a été modifié');
    }

    public function destroy(Post $post){
      $this->authorize('delete', $post);
      $post->delete();
      return redirect()->route('admin.posts.index')->with('success','Article supprimer');
    }

    private function params($request){
      $user = Auth::user();
      if($user->can('changeOwner', Post::class)){
        return $request->all();
      }
      else{
        $params = $request->except('user_id');
        $params['user_id'] = $user->id;
        return $params;
      }
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Category;
use App\Comment;
use App\Post;
use App\User;
use App\Repository\PostRepository;

class PostController extends Controller
{
    private $per_page = 5;
    private $post_r;
    private $category_model;
    private $post_model;
    private $user_model;

    public function __construct(PostRepository $post_r,  Category $category_model, Post $post_model, User $user_model){
      $this->post_r = $post_r;
      $this->category_model = $category_model;
      $this->post_model = $post_model;
      $this->user_model = $user_model;
    }

    public function index()
    {
      $posts = $this->post_r->getPosts()->paginate($this->per_page);
      $categories =  $this->category_model->newQuery()->get();
      return view('posts/index', [
            'posts' => $posts,
            'categories' => $categories
        ]);
    }

    public function category($slug)
    {
        $categories =  $this->category_model->newQuery()->get();
        $category = $this->category_model->newQuery()->where('slug', '=', $slug)->first();
        $posts = $this->post_model->newQuery()->with('category', 'user')->where('category_id', $category->id)->paginate($this->per_page);
        return view('posts.index',[
          'categories' => $categories,
          'category' => $category,
          'posts' => $posts
        ]);
    }

    public function user($user_id){
        $categories =  $this->category_model->newQuery()->get();
        $user = $this->user_model->find($user_id);
        $posts = $this->post_model->with('category', 'user')->where('user_id', $user->id)->paginate($this->per_page);
        return view('posts.index', compact('posts', 'user'),[
          'categories' => $categories,
          'user' => $user,
          'posts' => $posts
        ]);
    }

    public function show($slug){
      $post = $this->post_model->where('slug',$slug)->first();
      return view('posts.show',[
        'post' => $post
      ]);
    }




}

resources/views/admin/layout.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>@yield('title')</title>
    <link rel="icon" type="image/x-icon" href="{{ asset('favicon.ico') }}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
    <style>
        .navbar{
            margin-bottom: 2rem;
        }
    </style>
</head>

<body>

<nav class="navbar navbar-fixed-top navbar-toggleable-md navbar-inverse bg-primary">
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="{{ route('admin.posts.index') }}">Backend</a>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{{ route('admin.posts.index') }}">Posts</a>
            </li>
        </ul>
        <ul class="navbar-nav">
            <li class="nav-item active">
                <form action="{{ route('logout') }}" method="post" style="display: inline;">
                    {{ csrf_field() }}
                    <button class="nav-link" style="background-color: transparent; border: none;">logout</button>
                </form>
            </li>
        </ul>
    </div>
</nav>

<div class="container">
    @if (session('success'))
        <div class="alert alert-success">
            {{ session('success') }}
        </div>
    @endif

    @yield('content')
</div><!-- /.container -->

</body>
</html>

resources/views/admin/posts/edit.blade.php
@extends('admin.layout')

@section('content')
  <h1>Edit post</h1>
    <p>
        <a href="{{ route('admin.posts.index') }}">< Back to the list</a>
    </p>

    @include('admin.posts.form')
@endsection

resources/views/admin/posts/form.blade.php
{!! Form::model($post, [
    'route' => $post->id ? ['admin.posts.update', $post] : 'admin.posts.index',
    'method' => $post->id ? 'PUT' : 'POST'
]) !!}

    <div class="row">
        <div class="col-sm-6">
            <div class="form-group @if($errors->first('name')) has-danger @endif">
                {!! Form::label('name', 'Name') !!}
                {!! Form::text('name', null, ['class' => 'form-control']) !!}
                @if($errors->first('name'))
                <small class="form-control-feedback">{{ $errors->first('name') }}</small>
                @endif
            </div>
        </div>
        <div class="col-sm-6">
            <div class="form-group @if($errors->first('slug')) has-danger @endif">
                {!! Form::label('slug', 'Slug') !!}
                {!! Form::text('slug', null, ['class' => 'form-control']) !!}
                @if($errors->first('slug'))
                    <small class="form-control-feedback">{{ $errors->first('slug') }}</small>
                @endif
            </div>
        </div>
        <div class="col-sm-6">
            <div class="form-group @if($errors->first('category_id')) has-danger @endif">
                {!! Form::label('category_id', 'Category') !!}
                {!! Form::select('category_id', $categories, null, ['class' => 'form-control', 'required' => 'required']) !!}
                @if($errors->first('category_id'))
                    <small class="form-control-feedback">{{ $errors->first('category_id') }}</small>
                @endif
            </div>
        </div>
        @can('changeOwner', $post)
        <div class="col-sm-6">
            <div class="form-group @if($errors->first('user_id')) has-danger @endif">
                {!! Form::label('user_id', 'User') !!}
                {!! Form::select('user_id', $users, null, ['class' => 'form-control', 'required' => 'required']) !!}
                @if($errors->first('user_id'))
                    <small class="form-control-feedback">{{ $errors->first('user_id') }}</small>
                @endif
            </div>
        </div>
        @endcan
    </div>
    <div class="form-group @if($errors->first('content')) has-danger @endif">
        {!! Form::label('content', 'Content') !!}
        {!! Form::textarea('content', null, ['class' => 'form-control', 'required' => 'required']) !!}
        @if($errors->first('content'))
            <small class="form-control-feedback">{{ $errors->first('content') }}</small>
        @endif
    </div>
    {!! Form::submit($post->id ? 'Update' : 'Create', ['class' => 'btn btn-primary']) !!}
{!! Form::close() !!}

resources/views/admin/posts/index.blade.php
@extends('admin.layout')

@section('content')
  <h1>Gérer ses articles</h1>

    <p>
        <a href="{{ route('admin.posts.create') }}" class="btn btn-primary">Add a new post</a>
    </p>

    <table class="table table-striped">
      <thead>
        <tr>
          <th>ID</th>
          <th>Name</th>
          <th>Category</th>
          <th>Date de publication</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        @foreach ($posts as $post)
        <tr>
          <td>{{ $post->id }}</td>
          <td>{{ $post->name }}</td>
          <td>{{ $post->category->name }}</td>
          <td>{{ $post->created_at->format('d/m/Y H:i') }}</td>
          <td>
            @can('update', $post)
            <a href="{{ route('admin.posts.edit', ['id' => $post->id]) }}" class="btn btn-primary">Edit</a>
            @endcan
            @can('delete', $post)
            {!! Form::model($post, ['method' => 'DELETE', 'route' => ['admin.posts.destroy', $post], 'style' => 'display:inline;']) !!}
                {!! Form::submit('Delete', ['class' => 'btn btn-danger']) !!}
            {!! Form::close() !!}
            @endcan
          </td>
        </tr>
        @endforeach
      </tbody>
    </table>

    <div class="navigation">
        {{ $posts->links('vendor.pagination.bootstrap-4') }}
    </div>
@endsection

resources/views/admin/posts/new.blade.php
@extends('admin.layout')

@section('content')
  <h1>New post</h1>
    <p>
        <a href="{{ route('admin.posts.index') }}">< Back to the list</a>
    </p>

    @include('admin.posts.form')
@endsection

resources/views/layout.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>@yield('title', 'BlogMVC')</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
    <style>
        .navbar{
            margin-bottom: 2rem;
        }

        .text-right{
            text-align: right;
        }
    </style>
</head>

<body>

<nav class="navbar navbar-fixed-top navbar-toggleable-md navbar-inverse bg-primary">
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="{{ route('posts.index') }}">Blogmvc</a>
    <ul class="nav navbar-nav mr-auto">
        <li class="nav-item active">
            <a class="nav-link" href="{{ route('posts.index') }}">Blog</a>
            <p><a href="{{ route('posts.index') }}">Retour a la liste des articles</a></p>
        </li>
    </ul>
    <ul class="navbar-nav">
        <li class="nav-item active">
            <a class="nav-link" href="{{ route('admin.posts.index') }}">backend</a>
        </li>
    </ul>
</nav>

<div class="container">
  <main role="main">

      @if (session('success'))
          <div class="alert alert-success">
              {{ session('success') }}
          </div>
      @endif

      @yield('content')
  </main>

</div> <!-- /container -->

</body>
</html>

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>@yield('title', 'BlogMVC')</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
    <style>
        .navbar{
            margin-bottom: 2rem;
        }

        .text-right{
            text-align: right;
        }
    </style>
</head>

<body>

<nav class="navbar navbar-fixed-top navbar-toggleable-md navbar-inverse bg-primary">
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="{{ route('posts.index') }}">Blogmvc</a>
    <ul class="nav navbar-nav mr-auto">
        <li class="nav-item active">
            <a class="nav-link" href="{{ route('posts.index') }}">Blog</a>
        </li>
    </ul>
    <ul class="navbar-nav">
        <li class="nav-item active">
            <a class="nav-link" href="{{ route('admin.posts.index') }}">backend</a>
        </li>
    </ul>
</nav>

<div class="container">
  <main role="main">

      @if (session('success'))
          <div class="alert alert-success">
              {{ session('success') }}
          </div>
      @endif

      @yield('content')
  </main>

</div> <!-- /container -->

</body>
</html>

resources/views/posts/index.blade.php
@extends("layouts.app")




@section('content')
<style>
  .article{

  }
</style>
  <div class="container">
    <div class="row">
      <div class="col-md-8 article">
        @foreach($posts as $post)
            <h2><a href="{{ route('posts.show', ['slug' => $post->slug]) }}">{{ $post->name }}</a></h2>
            <p>
                <small>
                    Category : <a href="{{ route('posts.category', ['slug' => $post->category->slug]) }}">{{ $post->category->name }}</a>
                    by <a href="{{ route('posts.user', ['id' => $post->user->id]) }}">{{ $post->user->name }}</a>
                    on {{ $post->created_at->format('M dS Y') }}
                </small>
            </p>
            <p>
              {{ $post->getExtrait()}}
            <p class="text-right">
                <a href="{{ route('posts.show', ['slug' => $post->slug]) }}" class="btn btn-primary">Read more...</a>
            </p>
        @endforeach

        <div class="navigation">
          {{ $posts->links('vendor.pagination.bootstrap-4') }}
        </div>
      </div>

      <div class="col-md-3">
        <div class="list-group">
          @foreach ($categories as $category)
            <a class="list-group-item d-flex justify-content-between align-items-center" href="{{ route('posts.category', ['slug' => $category->slug]) }}">{{ $category->name }}</a>
          @endforeach
        </div>
      </div>

    </div>
  </div>


  <div class="container">

  </div>

@endsection

resources/views/posts/show.blade.php
@extends("sidebar")

@section('main')
  <div class="container">
    <div class="row">
      <div class="col-md-8">
        <p><a href="{{ route('posts.index') }}">Retour a la liste des articles</a></p>
        <h1>{{ $post->name }}</h1>
        <p>
          <small>
              Category : <a href="">{{ $post->category->name }}</a>
              by <a href="">{{ $post->user->name }}</a>
              on {{ $post->created_at->format('M dS Y') }}
          </small>
        </p>
        <p>
          {{ $post->content }}
        </p>
        <p>&nbsp;</p><!-- I know.... -->

      </div>
    </div>
  </div>
@endsection

resources/views/sidebar.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-sm-8">
            @yield('main')
        </div>
        <div class="col-sm-4">

        </div>
    </div>
@endsection